// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrsjgfqmslqdjwxaulyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yc2pnZnFtc2xxZGp3eGF1bHlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDk3MTMsImV4cCI6MjA2NzIyNTcxM30.xJvn3JiWwOl-xNuQYEfISU0fvGl0DiS3BT1TTchfH2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});